### ISSUE TITLE
Database setup: missing description or backup file

### ISSUE THREAD

**Issue by etnann** [MohammadHasham/Library-Management-Sytem#1]
Hi, could you share also the table description or SQL backup file of the MySQL database, so that one can completely setup the project? Thank you.

**Comment by ghost** [comment]
yes please there is no database backup for this project.

**Comment by MuhammadHasham23** [comment]
I am afraid, I don't have that file now since the project was just intended for learning. However, if someone can come up with a database design it would be great.
Feel free to generate a PR.

**Comment by mimowryy** [comment]
the database name is lms and the tables idk, can someone help me : D

**Comment by mimowryy** [comment]
i really do wanna see the whole website
